### ISSUE TITLE
Deleted /mayfield/data/user

### ISSUE THREAD

**Issue by amalnanavati** [KuriRobot/Kuri-Documentation#36]
I realized today that **all** the contents of `/mayfield/data/user` got deleted. I am not sure how they could have gotten deleted. The only possible causes I can think of are:

1. My Kuri did crash today while `catkin build`ing a library, and I had to force shut it down.
2. Independently, I ended up forcibly turning my Kuri off multiple times today (with the power button on the bottom) while it was running its shutdown routine.

The other possibly-relevant finding is that I had a USB drive attached to the Kuri, which got completely corrupted for unknown reasons.

Anyway, I do have access to another Kuri with a populated `/mayfield/data/user` directory. I have considered copying the files over, but before that I wanted to check: are all the files in that directory generic to all Kuri's, or are there Kuri-specific files (unique IDs and such)? If there are Kuri-specific files, could you point me towards which files I should modify, and how, to effectively re-populate the `/mayfield/data/user` on the deleted Kuri?

(Also, if you have ideas as to why the directory got deleted in the first place, that would be useful so that it doesn't happen again.)

**Comment by amalnanavati** [comment]
Never mind, it seems like the Kuri automatically restored these files on startup. I'm not sure what happened to delete these files, but they are there now :)

**Comment by amalnanavati** [comment]
By the way, @po1 or others, if you could point me to where the backup data is stored (the data that gets copied to `/mayfield/data/user` if that directory gets deleted/corrupted) and how to access it, that would be useful. Thanks!

**Comment by po1** [comment]
There is no backup.
What I believe happened:

- when you booted Kuri with an external drive plugged in, the external drive was mistaken for the internal SD card (which contains user data)
- when Kuri can't read useful data from its SD card, it reprovisions it: erases everything on it, formats it, encrypts it, creates user data folder structures. That explains why your external drive got "corrupted".
- once reprovisioned, you would see no data in `/mayfield/data/user` since it was just reset
- when you removed the external drive and rebooted Kuri, it would see its own internal SD card again and happily mount it as it always did. And your user data is back.
